DROP TABLE "CHARGING_PLACE" CASCADE CONSTRAINTS;
DROP TABLE "SECONDARY_ELEMENTS" CASCADE CONSTRAINTS;
DROP TABLE "ELEMENT" CASCADE CONSTRAINTS;
DROP TABLE "SPELL" CASCADE CONSTRAINTS;
DROP TABLE "ELEMENT_SPECIALIZATION" CASCADE CONSTRAINTS;
DROP TABLE "SPECIALIZATION" CASCADE CONSTRAINTS;
---
DROP TABLE "GRIMOIRE" CASCADE CONSTRAINTS;
DROP TABLE "SCROLL" CASCADE CONSTRAINTS;
DROP TABLE "MAGICAL_BEING" CASCADE CONSTRAINTS;
DROP TABLE "MAGICAL_BEING_CAN_HAVE" CASCADE CONSTRAINTS;
DROP TABLE "MAGICAL_BEING_HAD" CASCADE CONSTRAINTS ;